//! Release suggestion manager — files release beads when backports complete.
//!
//! When backport completeness is achieved (all critical backports merged for
//! a release branch), this module files a `chore` bead tagged with
//! `rodgers:type=release` that triggers the release management workflow.
//!
//! Per plan/backport-plan.md §Integration with Release Management:
//! - If all critical backports are merged, file release suggestion bead
//! - Release manager handles actual release cut
//!
//! ## Release suggestion bead
//!
//! - type: chore
//! - tag: rodgers:type=release
//! - title: "Release Suggestion: {branch_name}"
//! - acceptance: "{version} is released or explicitly declined"
//!
//! The bead links back to all critical backport beads that triggered it.

use tracing::info;

use crate::RogersError;
use crate::backport::completeness::CompletenessResult;
use crate::beads::client::{BeadClient, BeadResult};

/// Result of filing a release suggestion.
#[derive(Debug, Clone)]
pub struct ReleaseSuggestionResult {
    /// The release branch that triggered the suggestion.
    pub release_branch: String,
    /// The bead ID for the release suggestion.
    pub bead_id: String,
    /// Number of backport beads included in the suggestion.
    pub backports_included: usize,
    /// Whether the suggestion bead was filed successfully.
    pub success: bool,
    /// Any errors encountered.
    pub errors: Vec<String>,
}

/// File a release suggestion bead for a complete release branch.
///
/// When all critical backports for a release branch are merged, Rodgers
/// files a release suggestion bead. This bead is picked up by the release
/// manager workflow (per plans/release-management-plan.md) for actual
/// release cut.
///
/// # Arguments
/// - `result`: The completeness result for the branch
/// - `backport_bead_ids`: IDs of critical backport beads that completed
pub async fn file_release_suggestion(
    result: &CompletenessResult,
    backport_bead_ids: &[String],
) -> Result<ReleaseSuggestionResult, RogersError> {
    info!(
        "Filing release suggestion for {} ({} critical backports closed)",
        result.release_branch, result.critical_closed
    );

    let title = format!("Release Suggestion: {}", result.release_branch);

    let description = build_release_suggestion_description(result, backport_bead_ids);

    let acceptance = format!(
        "{} is released or explicitly declined",
        result.release_branch
    );

    // File the release suggestion bead
    let filed = file_suggestion_bead(&title, &description, &acceptance, backport_bead_ids).await;

    match filed {
        Ok(bead_result) => {
            info!(
                "Release suggestion bead filed: {} for {}",
                bead_result.id, result.release_branch
            );
            Ok(ReleaseSuggestionResult {
                release_branch: result.release_branch.clone(),
                bead_id: bead_result.id,
                backports_included: backport_bead_ids.len(),
                success: true,
                errors: vec![],
            })
        }
        Err(e) => {
            let msg = format!("Failed to file release suggestion: {}", e);
            tracing::error!("{}", msg);
            Ok(ReleaseSuggestionResult {
                release_branch: result.release_branch.clone(),
                bead_id: String::new(),
                backports_included: backport_bead_ids.len(),
                success: false,
                errors: vec![msg],
            })
        }
    }
}

/// Build the description for a release suggestion bead.
fn build_release_suggestion_description(
    result: &CompletenessResult,
    backport_bead_ids: &[String],
) -> String {
    let backport_links = backport_bead_ids
        .iter()
        .map(|id| format!("- {}", id))
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        "Plan: plans/backport-plan.md §Integration with Release Management\n\
        Plan: plans/release-management-plan.md\n\n\
        All critical backports for {branch} have been merged.\n\
        Release candidate is ready for human review.\n\n\
        ## Backports Included\n\n\
        {backports}\n\n\
        ## Details\n\n\
        - Critical backports: {critical} (all merged)\n\
        - Non-critical backports closed: {non_critical}\n\
        - Total beads: {total}\n\n\
        ## Next Steps\n\n\
        1. Review the included backports for correctness\n\
        2. Verify CI is green on {branch}\n\
        3. If approved, the release manager will create a release proposal\n\n\
        _This bead was auto-generated by Rodgers when all critical backports completed._",
        branch = result.release_branch,
        backports = if backport_links.is_empty() {
            "(none)".to_string()
        } else {
            backport_links
        },
        critical = result.critical_closed,
        non_critical = result.non_critical_closed,
        total = result.total_beads,
    )
}

/// Submit a release suggestion bead via `bd create`.
async fn file_suggestion_bead(
    title: &str,
    description: &str,
    acceptance: &str,
    backport_deps: &[String],
) -> Result<BeadResult, RogersError> {
    let mut client = BeadClient::new()
        .file_bead(title, description, "chore")
        .with_tag("rodgers:type=release")
        .with_priority(2) // Standard priority; critical triggers faster review
        .with_acceptance(acceptance);

    // Link back to the completed backport beads
    for dep in backport_deps {
        client = client.with_deps(&format!("discovered-from:{}", dep));
    }

    client.submit().await
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::backport::completeness::BackportBeadInfo;

    fn make_result(branch: &str, critical: usize, critical_closed: usize) -> CompletenessResult {
        let beads: Vec<_> = (0..critical)
            .map(|i| BackportBeadInfo {
                id: format!("bp-{}", i),
                target_branch: branch.to_string(),
                is_critical: true,
                is_closed: i < critical_closed,
                source_sha: Some("abc123".to_string()),
                source_pr: Some(42),
            })
            .collect();

        let remaining: Vec<_> = beads.iter().filter(|b| !b.is_closed).cloned().collect();

        CompletenessResult {
            release_branch: branch.to_string(),
            total_beads: critical,
            critical_beads: critical,
            critical_closed,
            non_critical_closed: 0,
            is_complete: critical_closed == critical,
            remaining_beads: remaining,
        }
    }

    #[test]
    fn test_release_suggestion_title_format() {
        let title = format!("Release Suggestion: {}", "release/1.x");
        assert_eq!(title, "Release Suggestion: release/1.x");
    }

    #[test]
    fn test_build_description_with_backports() {
        let result = make_result("release/1.x", 3, 3);
        let deps = vec!["bp-0".to_string(), "bp-1".to_string(), "bp-2".to_string()];
        let desc = build_release_suggestion_description(&result, &deps);

        assert!(desc.contains("Plan: plans/backport-plan.md"));
        assert!(desc.contains("Plan: plans/release-management-plan.md"));
        assert!(desc.contains("release/1.x"));
        assert!(desc.contains("All critical backports"));
        assert!(desc.contains("- bp-0"));
        assert!(desc.contains("- bp-1"));
        assert!(desc.contains("- bp-2"));
        assert!(desc.contains("Critical backports: 3"));
        assert!(desc.contains("Next Steps"));
    }

    #[test]
    fn test_build_description_without_backports() {
        let result = make_result("release/2.x", 0, 0);
        let desc = build_release_suggestion_description(&result, &[]);

        assert!(desc.contains("release/2.x"));
        assert!(desc.contains("(none)"));
        assert!(desc.contains("Critical backports: 0"));
    }

    #[test]
    fn test_release_suggestion_result_structure() {
        let result = ReleaseSuggestionResult {
            release_branch: "release/1.x".to_string(),
            bead_id: "suggest-1".to_string(),
            backports_included: 3,
            success: true,
            errors: vec![],
        };

        assert_eq!(result.release_branch, "release/1.x");
        assert_eq!(result.bead_id, "suggest-1");
        assert_eq!(result.backports_included, 3);
        assert!(result.success);
        assert!(result.errors.is_empty());
    }

    #[test]
    fn test_release_suggestion_result_with_errors() {
        let result = ReleaseSuggestionResult {
            release_branch: "release/2.x".to_string(),
            bead_id: String::new(),
            backports_included: 2,
            success: false,
            errors: vec!["bd create failed".to_string()],
        };

        assert!(!result.success);
        assert_eq!(result.errors.len(), 1);
        assert_eq!(result.errors[0], "bd create failed");
    }
}
